/// Flutter icons Football
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Football
///      fonts:
///       - asset: fonts/Football.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Football {
  Football._();

  static const _kFontFam = 'Football';

  static const IconData football = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData field = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData player = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData exchange = const IconData(0xe803, fontFamily: _kFontFam);
}
